import json
from typing import Dict, List, Optional
from dataclasses import dataclass, field

@dataclass
class SubTask:
    id: str
    description: str
    dependencies: List[str] = field(default_factory=list)
    status: str = "pending" # pending, in_progress, completed, failed
    result: Optional[str] = None

class DAGTracker:
    """Hierarchical DAG Builder and Execution Tracker for complex tasks."""
    def __init__(self):
        self.tasks: Dict[str, SubTask] = {}
        
    def load_from_json(self, plan_json: List[Dict]):
        """Load and initialize the plan generated by the LLM Planner Module."""
        self.tasks.clear()
        for t in plan_json:
            # Ensure it has basic keys
            task_id = t.get("id", str(len(self.tasks)))
            self.tasks[task_id] = SubTask(
                id=task_id,
                description=t.get("description", "Unknown task"),
                dependencies=t.get("dependencies", [])
            )
            
    def get_ready_tasks(self) -> List[SubTask]:
        """Returns tasks that are pending and have all dependencies completed."""
        ready = []
        for task in self.tasks.values():
            if task.status == "pending":
                deps_met = all(
                    dep in self.tasks and self.tasks[dep].status == "completed" 
                    for dep in task.dependencies
                )
                if deps_met:
                    ready.append(task)
        return ready
        
    def start_task(self, task_id: str):
        if task_id in self.tasks:
            self.tasks[task_id].status = "in_progress"
            
    def complete_task(self, task_id: str, result: str = ""):
        if task_id in self.tasks:
            self.tasks[task_id].status = "completed"
            self.tasks[task_id].result = result
            
    def fail_task(self, task_id: str, error: str = ""):
        if task_id in self.tasks:
            self.tasks[task_id].status = "failed"
            self.tasks[task_id].result = error
            
    def get_plan_state(self) -> str:
        """Roadmap Visibility: Return a string representing the roadmap."""
        lines = ["\n=== EXECUTION ROADMAP ==="]
        for t in self.tasks.values():
            symbol = " "
            if t.status == "completed": symbol = "✓"
            elif t.status == "failed": symbol = "✗"
            elif t.status == "in_progress": symbol = "▶"
            lines.append(f"[{symbol}] {t.id}: {t.description}")
        lines.append("=========================\n")
        return "\n".join(lines)
        
    def is_fully_completed(self) -> bool:
        if not self.tasks:
            return False
        return all(t.status == "completed" for t in self.tasks.values())
